---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  telco-gitops/rwn: telco-gitops

resources:
- 00-master-schedulable.yaml
- 01-config-ingress.yaml
- 50-worker-fix-ipi-rwn.yaml
