apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: local-block
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
        - key: cluster.ocs.openshift.io/openshift-storage
          operator: In
          values:
            - ""
  storageClassName: localblock
  volumeMode: Block
  fstype: ""
  maxDeviceCount: 1  # <-- Number of devices to be used per node
  deviceInclusionSpec:
    deviceTypes:
    - disk
    deviceMechanicalProperties:
    - NonRotational
    models: # (optional) list of models to allow
      - Dell Express Flash NVMe P4610 3.2TB SFF
    #vendors: # (optional) list of device vendors to allow
    #  - ATA # < -- CHANGEME
