# lso-profile1.yaml
---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: lso-profile1
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: ran.openshift.io/lso-profile1
          operator: Exists
  storageClassDevices:
    - storageClassName: "lso-profile1"
      volumeMode: Filesystem
      fsType: xfs
      # Update to match profile composition
      devicePaths:
        - /dev/sdb
        # - /dev/nvme1n2
        # - /dev/nvme2n1
