---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-telco-shift-zone-cnf-open5gs
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://api.core.telco.shift.zone:6443'
  project: default
  source:
    path: cnf/open5gs
    repoURL: 'https://github.com/openshift-telco/telco-gitops.git'
    targetRevision: HEAD