---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  telco-gitops/combined-core-ran: telco-gitops

bases:
  # Enable SCTP
  - ../../base/configs/sctp
  # SRIOV
  - ../../base/operators/openshift-sriov-network-operator
  # PAO (4.7)
  - ../../base/operators/openshift-performance-addon-operator
  # PTP
  - ../../base/operators/openshift-ptp
  # Intel vRAN Acceleration Operators
  # - ../../base/operators/vran-acceleration-operators
  # Removes OCP Web Console
  # - ../../configs/web-console

resources:
  - 01-max-pods-500.yaml
  - 02-ran-du-mcp.yaml
  - 50-ran-du-disable-chronyd.yaml
  # TODO: replace by ks8 job
  - 01-mcp.yaml

patches:
# TODO: replace by k8s job
- 01-patch-mcp-master.yaml
