---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-gitops-pre-hook.yaml  
  - 05-agentserviceconfig.yaml
  # - 06-bmc-pool5.yaml
  # - 06-bmc-telco-kvm02-sushy.yaml