---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    # openshift.io/run-level: "1"
  name: openshift-performance-addon-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: performance-addon-operator
  namespace: openshift-performance-addon-operator
---
### Create Catalog Source with prerelease image
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: performance-addon-operator
  namespace: openshift-marketplace
spec:
  displayName: Openshift Performance Addon Operator
  icon:
    base64data: ""
    mediatype: ""
  image: quay.io/openshift-kni/performance-addon-operator-index:4.8-snapshot
  publisher: Red Hat
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: performance-addon-operator-subscription
  namespace: openshift-performance-addon-operator
spec:
  channel: "4.8"
  installPlanApproval: Automatic
  name: performance-addon-operator
  # Modify source name of the catalogsource for air-gapped deployments
  source:  performance-addon-operator
  sourceNamespace: openshift-marketplace
